In [1]:
import kquant as kq
import datetime as dt
import logging

In [2]:
# API_account
def set_api_account():
    kq.set_api("KRX2308020", "EQDkUcyI3dK6oIAXqAR8BXOK4bKxHHmH")
    return None

set_api_account()

In [5]:
symbol_stock_df = kq.symbol_stock()
symbol_stock_df

,ISIN,SYMBOL,NAME,NAME_EN,SEC_TYPE,ADMIN_ISSUE,MARKET
0,HK0000057197,900110,이스트아시아홀딩스,East Asia Holdings,FS,0,코스닥
1,HK0000214814,900270,헝셩그룹,HENG SHENG GROUP,FS,0,코스닥
2,HK0000295359,900260,로스웰,Rothwell,FS,0,코스닥
3,HK0000307485,900290,GRT,GRT,FS,0,코스닥
4,HK0000312568,900300,오가닉티코스메틱,ORGANIC TEA COSMETICS,FS,91,코스닥
...,...,...,...,...,...,...,...
"3,762",KYG2114A1094,900120,씨케이에이치,CKH,FS,91,코스닥
"3,763",KYG2115T1076,900250,크리스탈신소재,Crystal New Material,FS,0,코스닥
"3,764",KYG3931T1076,900070,글로벌에스엠,GSMT,FS,0,코스닥
"3,765",KYG5307W1015,900140,엘브이엠씨홀딩스,LVMC Holdings,FS,0,유가증권
"3,766",USU652221081,900100,애머릿지,Ameridge,FS,0,코스닥

In [6]:
rank_stocks_df = kq.rank_stocks()
rank_stocks_df

,SYMBOL,OPEN,HIGH,LOW,CLOSE,VOLUME,AMOUNT,PREV_CLOSE,CHG_PCT,CHG_TYPE,MARKETCAP,NAME,NAME_EN,SEC_TYPE,MARKET
0,005930,"71,300","71,700","70,200","70,200","15,951,435","1,127,919,218,700","72,000",-2.5000,5,"419,078,735,010,000",삼성전자,SamsungElec,ST,유가증권
1,373220,"513,000","514,000","505,000","507,000","164,694","83,557,984,000","514,000",-1.3619,5,"118,638,000,000,000",LG에너지솔루션,LG Energy Solution,ST,유가증권
2,000660,"120,300","122,900","118,800","119,000","2,350,746","282,005,567,300","122,400",-2.7778,5,"86,632,281,435,000",SK하이닉스,SK hynix,ST,유가증권
3,207940,"733,000","740,000","731,000","732,000","41,850","30,758,642,000","731,000",0.1368,2,"52,099,368,000,000",삼성바이오로직스,SAMSUNG BIOLOGICS,ST,유가증권
4,005490,"591,000","605,000","584,000","603,000","1,390,021","828,934,493,000","584,000",3.2534,2,"50,996,451,690,000",POSCO홀딩스,POSCO Holdings,ST,유가증권
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
"3,762",426410,"13,580","13,580","13,425","13,485",166,"2,232,585","13,425",0.4469,2,"2,022,750,000",ARIRANG 미국대체투자Top10MV,ARIRANG Top10 US Listed Alt Managers MV,EF,유가증권
"3,763",433870,"10,890","10,890","10,890","10,890",3,"32,670","10,940",-0.4570,5,"1,960,200,000",ARIRANG TDF2050액티브,ARIRANG TDF2050 Active,EF,유가증권
"3,764",287330,"6,060","6,080","6,040","6,080",757,"4,595,035","6,075",0.0823,2,"1,337,600,000",KBSTAR 200생활소비재,KBSTAR 200 Con&Sta,EF,유가증권
"3,765",315480,"10,800","10,835","10,740","10,745",147,"1,581,355","10,805",-0.5553,5,"1,289,400,000",KBSTAR 200커뮤니케이션서비스,KBSTAR 200CS,EF,유가증권
"3,766",287320,"11,920","11,950","11,920","11,930",10,"119,355","11,925",0.0419,2,"1,193,000,000",KBSTAR 200산업재,KBSTAR 200 Industrials,EF,유가증권

In [7]:
account_code_df = kq.account_code()
account_code_df

    ACCOUNT_CODE                NAME               NAME_EN    UNIT
0         111000            자산총계          Total Assets    천원
1         111100            유동자산        Current Assets    천원
2         111600          비유동자산    Non-current Assets    천원
3         113000            부채총계     Total Liabilities    천원
4         113100            유동부채   Current Liabilities    천원
..           ...                 ...                   ...     ...
707       706600  전체시가총액(평균)   All Mkt. Cap.(Avg.)  백만원
708       701100              액면가             Par Value   원/주
709       707000            종업원수              Employee      명
710       707200            공시지가            Land Price    천원
711       151000    비교재무제표정보  Comparative FS Info.    Text

[712 rows x 4 columns]

In [10]:
account_code_df[account_code_df['ACCOUNT_CODE'] == "115000"]

  ACCOUNT_CODE      NAME                     NAME_EN  UNIT
7       115000  자본총계  Total Stockholders' Equity  천원

In [5]:
symbols = [
    "005930",
    "373220",
    "000660",
    "207940",
    "005490",
]
symbols_and_orders = [
    (symbols[0], 1),
    (symbols[0], 2),
    (symbols[1], 10),
    (symbols[2], 10),
    (symbols[3], 10),
    (symbols[4], 10),
]

symbols_and_orders = [
    (symbols[0], 3),
    (symbols[1], 10),
    (symbols[2], 10),
    (symbols[3], 10),
    (symbols[4], 10),
]

In [3]:
def trade_func(
    date: dt.date,
    dict_df_result: dict[str, pd.DataFrame],
    dict_df_position: dict[str, pd.DataFrame],
    logger: logging.Logger,
) -> list[tuple[str, int]]:
    r"""주식매매 지시함수

    주식매매 지시함수에 대한 설명

    :param dt.date date: 매매일 날짜
    :param dict[str, pd.DataFrame] dict_df_result: 매매일까지의 주문 및 체결 정보
    :param dict[str, pd.DataFrame] dict_df_position: 매매일의 주식 보유 정보
    :param logging.Logger logger: 로거
    :return list[tuple[str, int]]: 주식매매 지시
    """

    # 본 예제코드는 코드가 실제로 실행되는 것을 보여주기 위해
    # 심사 투자기간이 2023년 1월 2일부터 시작된다고 가정하고 있습니다.
    # 실제 제출코드에서는 실제 심사 투자기간을 사용해야 합니다.

    # 시가총액 상위 5개 주식
    symbols = [
        "005930",
        "373220",
        "000660",
        "207940",
        "005490",
    ]

    if date == dt.date(2023, 1, 2):  # 투자 시작일
        # 각 종목을 10주씩 매수
        symbols_and_orders = [
            (symbols[0], 1),
            (symbols[0], 2),
            (symbols[1], 10),
            (symbols[2], 10),
            (symbols[3], 10),
            (symbols[4], 10),
        ]
    elif date.weekday() == 1:  # 매주 화요일마다
        # 각 종목을 추가적으로 1주씩 매수
        symbols_and_orders = [
            (symbols[0], 0),
            (symbols[1], -10),
            (symbols[2], -10),
            (symbols[3], -10),
            (symbols[4], -10),
        ]
    else:
        symbols_and_orders = []

    return symbols_and_orders

In [4]:
# 초기 매매일 코드
dict_df_result, dict_df_position, logger = kq.backtest_stock_port_daily(
    trade_func,
    "2023-01-02",
    "2023-01-02",
    init_cash=1_000_000_000,
    return_position=True,
    return_logger=True,
)

<KQuantDuplicatedSymbolInPort> 중복된 주식 종목 단축코드: 005930
[2023-01-02] 종목: 373220, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 000660, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 207940, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 005490, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10

In [194]:
# 초기 매매일 이후 CHECK-API 시스템이 정상가동하는 최종 매매일 까지 코드
from dateutil.parser import parse

date = parse("2023-01-03")
symbols_and_orders = trade_func(date, dict_df_result, dict_df_position, logger)

dict_df_result, dict_df_position = kq.backtest_update_stock_port_daily(
    symbols_and_orders,
    date,
    dict_df_result,
    dict_df_position,
)

[2023-01-03] 종목: 373220, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0
[2023-01-03] 종목: 000660, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0
[2023-01-03] 종목: 207940, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0
[2023-01-03] 종목: 005490, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0

In [145]:
symbol_result_df = dict_df_result["005930"]
_current_price = symbol_result_df.sort_values("DATE").tail(1)["PRICE"].values[0]

symbol_position_df = dict_df_position["005930"]

_trade_price = dict_df_position["005930"]["TRADE_PRICE"].values[0]
_current_qty = dict_df_position["005930"]["QTY"].values[0]

In [167]:
class STATUS_LOADER:
    def __init__(self, dict_df_result, dict_df_position) -> None:
        self.dict_df_result = dict_df_result
        self.dict_df_position = dict_df_position

    def get_current_cash(self):
        _dict_df_result = self.dict_df_result
        try:
            _df_result_total = _dict_df_result["TOTAL"]
            _current_cash = (
                _df_result_total.sort_values("DATE").tail(1)["CASH"].values[0]
            )
            return _current_cash
        except:
            return 1_000_000_000
    

    def get_current_symbol_df(self):
        current_symbol_list = list()
        _dict_df_result = self.dict_df_result
        _dict_df_position = self.dict_df_position
        
        _total_symbols = sorted(_dict_df_position.keys())

        for _symbol in _total_symbols:
            try:
                _symbol_result_df = _dict_df_result[_symbol]
                _symbol_position_df = _dict_df_position[_symbol]

                _current_price = (
                    _symbol_result_df.sort_values("DATE").tail(1)["PRICE"].values[0]
                )
                _trade_price = _symbol_position_df["TRADE_PRICE"].values[0]
                _current_qty = _symbol_position_df["QTY"].values[0]

                current_symbol_list.append(
                    {
                        "symbol": _symbol,
                        "current_qty": _current_qty,
                        "current_price": _current_price,
                        "trade_price": _trade_price,
                    }
                )
            except:
                pass
        return pd.DataFrame(current_symbol_list)

In [180]:
status_loader = STATUS_LOADER(dict_df_result, dict_df_position)
current_cash = status_loader.get_current_cash()
current_symbol_df = status_loader.get_current_symbol_df()

In [ ]:
def trade_func(
    date: dt.date,
    dict_df_result: dict[str, pd.DataFrame],
    dict_df_position: dict[str, pd.DataFrame],
    logger: logging.Logger,
) -> list[tuple[str, int]]:
    status_loader = STATUS_LOADER(dict_df_result, dict_df_position)
    current_cash = status_loader.get_current_cash()
    current_symbol_df = status_loader.get_current_symbol_df()

In [185]:
def trade_func(
    date: dt.date,
    dict_df_result: dict[str, pd.DataFrame],
    dict_df_position: dict[str, pd.DataFrame],
    logger: logging.Logger,
) -> list[tuple[str, int]]:
    status_loader = STATUS_LOADER(dict_df_result, dict_df_position)
    status_loader.get_current_cash()
    df = status_loader.get_current_symbol_df()
    print(df)
    r"""주식매매 지시함수

    주식매매 지시함수에 대한 설명

    :param dt.date date: 매매일 날짜
    :param dict[str, pd.DataFrame] dict_df_result: 매매일까지의 주문 및 체결 정보
    :param dict[str, pd.DataFrame] dict_df_position: 매매일의 주식 보유 정보
    :param logging.Logger logger: 로거
    :return list[tuple[str, int]]: 주식매매 지시
    """

    # 본 예제코드는 코드가 실제로 실행되는 것을 보여주기 위해
    # 심사 투자기간이 2023년 1월 2일부터 시작된다고 가정하고 있습니다.
    # 실제 제출코드에서는 실제 심사 투자기간을 사용해야 합니다.

    # 시가총액 상위 5개 주식
    symbols = [
        "005930",
        "373220",
        "000660",
        "207940",
        "005490",
    ]

    if date == dt.date(2023, 1, 2):  # 투자 시작일
        # 각 종목을 10주씩 매수
        symbols_and_orders = [
            (symbols[0], 10),
            (symbols[1], 10),
            (symbols[2], 10),
            (symbols[3], 10),
            (symbols[4], 10),
        ]
    elif date.weekday() == 1:  # 매주 화요일마다
        # 각 종목을 추가적으로 1주씩 매수
        symbols_and_orders = [
            (symbols[0], -7),
            (symbols[1], -10),
            (symbols[2], -10),
            (symbols[3], -10),
            (symbols[4], -10),
        ]
    else:
        symbols_and_orders = []

    return symbols_and_orders

In [186]:
# 초기 매매일 코드
dict_df_result, dict_df_position, logger = kq.backtest_stock_port_daily(
    trade_func,
    "2023-01-02",
    "2023-01-02",
    init_cash=1_000_000_000,
    return_position=True,
    return_logger=True,
)

[2023-01-02] 종목: 005930, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 373220, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 000660, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10
[2023-01-02] 종목: 207940, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10

Empty DataFrame
Columns: []
Index: []

[2023-01-02] 종목: 005490, 주문전 보유수량:      0 주문수량:     10, 매매수량:     10, 주문후 보유수량:     10

In [187]:
# 초기 매매일 이후 CHECK-API 시스템이 정상가동하는 최종 매매일 까지 코드
from dateutil.parser import parse

date = parse("2023-01-03")
symbols_and_orders = trade_func(date, dict_df_result, dict_df_position, logger)

dict_df_result, dict_df_position = kq.backtest_update_stock_port_daily(
    symbols_and_orders,
    date,
    dict_df_result,
    dict_df_position,
)

[2023-01-03] 종목: 005930, 주문전 보유수량:     10 주문수량:     -7, 매매수량:     -7, 주문후 보유수량:      3
[2023-01-03] 종목: 373220, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0
[2023-01-03] 종목: 000660, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0
[2023-01-03] 종목: 207940, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0

   symbol  current_qty  current_price  trade_price
0  000660           10         75,700       75,700
1  005490           10        272,000      272,000
2  005930           10         55,500       55,500
3  207940           10        827,000      827,000
4  373220           10        446,000      446,000

[2023-01-03] 종목: 005490, 주문전 보유수량:     10 주문수량:    -10, 매매수량:    -10, 주문후 보유수량:      0

In [188]:
# 초기 매매일 이후 CHECK-API 시스템이 정상가동하는 최종 매매일 까지 코드
from dateutil.parser import parse

date = parse("2023-01-04")
symbols_and_orders = trade_func(date, dict_df_result, dict_df_position, logger)

dict_df_result, dict_df_position = kq.backtest_update_stock_port_daily(
    symbols_and_orders,
    date,
    dict_df_result,
    dict_df_position,
)

   symbol  current_qty  current_price  trade_price
0  005930            3         55,400       55,500